@Thetis_HostAddress = http://localhost:5032
//@AuthCookie = thetis_cookie=CfDJ8P60pvhiA3ZEk1bbt2LaC0BPGnY9x5qQwd-_qeO6aPZLPXDmt2y5vshFctfzX9CgI3blh6NH7KlXXX5eui_9X2v3ZFujkwmPVZZnWSgK3CG-gRD4d0PLQSqGAQ24i5Xm0X690K_2kZM6s0QNwaWODoF9pXMUGZiDvQoXuIPgqil3Ifg2-5cxh9m50N57gwuTLrL-XAzIi7ny6CV1aSoSwUJFuqjVpA_69A4uA635dEqd9wOq6IwOyWbBjLlwRh5RlTglgHStkSQPl2O5IcyZOYTUPidZ3Hy-5QxaI7r8J7dxY-yZ0nK3nwtuT0eK1vNd6V5k8FnyPIFwxfsK_Z7RnsFwZoGVmsDUtai3ZfV--4r4Y5Tu4Szg968D_i7DZwXcC_boTW-voPsMu3oMjNWdE8Fwj4lWcorxWAxPtbMiwcChNAhhLLS1XFPt_6ZLC2rc_tbaq60hKXwaJMNXFzM3I8Y

### Login with user
POST {{Thetis_HostAddress}}/api/login
Content-Type: application/json
Accept: application/json

{
  "username": "Test.McTestFace",
  "password": "TestPassword123!"
}

### Get User Details
GET {{Thetis_HostAddress}}/api/users/me
Accept: application/json

### Add a new role
POST {{Thetis_HostAddress}}/api/roles
Content-Type: application/json
Accept: application/json

{
  "name": "Administrator",
  "description": "Administrator role with full access",
  "claims": [
    {
      "claimType": "Permission",
      "claimValue": "CanCreateProfiles"
    },
    {
      "claimType": "Permission",
      "claimValue": "CanAdministerSystem"
    }
  ]
}

### Update an existing role
@Role_Id = 0198464d-09f8-786e-91cd-abd2c3fce3bb
PUT {{Thetis_HostAddress}}/api/roles/{{Role_Id}}
Content-Type: application/json
Accept: application/json

{
  "id": "{{Role_Id}}",
  "name": "Administrator2",
  "description": "Updated description for Administrator2 role",
  "claims": [
    {
      "claimType": "Permission",
      "claimValue": "CanCreateProfiles"
    },
    {
      "claimType": "Permission",
      "claimValue": "CanPublishToFhirServer"
    },
    {
      "claimType": "Permission",
      "claimValue": "CanAdministerSystem"
    }
  ]
}

### Get role by ID
GET {{Thetis_HostAddress}}/api/roles/{{Role_Id}}
Accept: application/json

### Delete a role
DELETE {{Thetis_HostAddress}}/api/roles/{{Role_Id}}
Accept: application/json

### Get all roles
@RolePageNumber = 1
@RolePageSize = 10
GET {{Thetis_HostAddress}}/api/roles?pageNumber={{RolePageNumber}}&pageSize={{RolePageSize}}
Accept: application/json


### Add a new user
POST {{Thetis_HostAddress}}/api/users
Content-Type: application/json
Accept: application/json

{
    "firstName": "Test",
    "lastName": "McTestFace",
    "username": "Test.McTestFace",
    "password": "TestPassword123!",
    "email": "jonh.doe@example.com"
}

### Update an existing user
@User_Id = 0198464b-f299-7a51-b0d8-d61bca4157bd
PUT {{Thetis_HostAddress}}/api/users/{{User_Id}}
Content-Type: application/json
Accept: application/json

{
  "id": "{{User_Id}}",
  "firstName": "Test",
  "lastName": "McTestFace",
  "username": "Test.McTestFace",
  "password": "TestPassword123!",
  "email": "Test.McTestFace@example.com",
  "roles": [
    {
      "id": "0198464d-09f8-786e-91cd-abd2c3fce3bb",
      "name": "Administrator"      
    }
  ]
}

### Get user by ID
GET {{Thetis_HostAddress}}/api/users/{{User_Id}}
Accept: application/json

### Delete a user
DELETE {{Thetis_HostAddress}}/api/users/{{User_Id}}
Accept: application/json

### Get all users

@UserPageNumber = 1
@UserPageSize = 10
GET {{Thetis_HostAddress}}/api/users?pageNumber={{UserPageNumber}}&pageSize={{UserPageSize}}
Accept: application/json

### Get profile by ID

@Profile_Id = 12345
GET {{Thetis_HostAddress}}/api/profiles/{{Profile_Id}}
Accept: application/json

### Get all profiles

@ProfilePageNumber = 1
@ProfilePageSize = 10
GET {{Thetis_HostAddress}}/api/profiles?pageNumber={{ProfilePageNumber}}&pageSize={{ProfilePageSize}}
ASccept: application/json