@Thetis_HostAddress = http://localhost:5032

// User Endpoints

### Get all users

GET {{Thetis_HostAddress}}/users
Accept: application/json

//Profile Endpoints

### Get profile by ID

@Profile_Id = 12345
GET {{Thetis_HostAddress}}/profiles/{{Profile_Id}}
Accept: application/json

### Get all profiles

@ProfilePageNumber = 1
@ProfilePageSize = 10
GET {{Thetis_HostAddress}}/profiles?pageNumber={{ProfilePageNumber}}&pageSize={{ProfilePageSize}}
ASccept: application/json